Feature/setup helpdesk
kitab-bazar/server pull request #21
Opened 2022-01-31 08:44 UTC by bimal125

- Depends on #18

## Changes

* Add mutations to create/update/delete faqs and contact messages
* Add queries to retrieve faqs and contact messages

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [x] permission checks (tests here too)
- [x] translations

2022-02-02 10:47 UTC, thenav56 requested changes

2022-02-02 10:47 UTC, thenav56 commented on apps/helpdesk/filters.py
> +        return queryset.filter(Q(question__icontains=value) | Q(question__icontains=value))
why?

2022-02-02 10:47 UTC, thenav56 commented on apps/helpdesk/models.py
> +        DRAFT = 'draft', "Draft"
```suggestion
        DRAFT = 'draft', 'Draft'
```

2022-02-02 10:47 UTC, thenav56 commented on apps/helpdesk/mutations.py
> +
return qs.none()

2022-02-02 10:47 UTC, thenav56 commented on apps/helpdesk/mutations.py
> +
return qs.none()

2022-02-02 11:14 UTC, bimal125 commented on apps/helpdesk/filters.py
> +        return queryset.filter(Q(question__icontains=value) | Q(question__icontains=value))
tyo should be question and answer

2022-02-03 09:07 UTC, bimal125 commented on apps/helpdesk/models.py
> +        DRAFT = 'draft', "Draft"
@thenav56  This is already changed.

2022-02-03 09:11 UTC, thenav56 approved these changes

2022-02-04 03:40 UTC, merged