Applying this commit will verify/unveify user
kitab-bazar/server pull request #46
Opened 2022-02-21 11:20 UTC by Rup-Narayan-Rajbanshi

- Addresses User

## Changes
- Verify/Unverify User

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-02-21 12:11 UTC, thenav56 requested changes

2022-02-21 12:11 UTC, thenav56 commented on apps/user/serializers.py
> +class VerifySerializer(serializers.Serializer):
Let's Use ModelSerializer, and use fields = ('is_verified',)
```suggestion
class UserVerifySerializer(serializers.ModelSerializer):
```

2022-02-21 12:11 UTC, thenav56 commented on apps/user/serializers.py
> +        raise serializers.ValidationError(gettext('User with this id doesnot exists'))
Let's never change the database entity through validation.
We have basic mutation where you can specify custom permissions like this one. Add permission in configs/permissions.py VERIFY_USER, and then mention that permission using CreateUpdateGrapheneMutation with id. That way you don't have to retrieve the user yourself and validate user permissions.

https://github.com/kitab-bazar/server/blob/afbb95ec58e110851ca6196c8855d5aebcbb29bd/apps/order/mutations.py#L95-L102

```suggestion
    def validate(self, data):
        user_type = self.context['request'].user.user_type
        if not user_type == User.UserType.MODERATOR:
            raise serializers.ValidationError(gettext('Permission denied'))
        return data
```

2022-02-21 12:11 UTC, thenav56 commented on apps/user/mutations.py
> +class Verify(graphene.Mutation):
Using CreateUpdateMutation here
https://github.com/kitab-bazar/server/blob/afbb95ec58e110851ca6196c8855d5aebcbb29bd/apps/order/mutations.py#L95-L102

2022-02-22 05:11 UTC, frozenhelium commented
@Rup-Narayan-Rajbanshi 
Commit message should be an Imperative Sentence

eg:
`Add model and mutation for user verification`

2022-02-22 10:22 UTC, thenav56 requested changes
Let's
- Add tests.
- Add verfied_by as well

2022-02-22 10:22 UTC, thenav56 commented on apps/user/filters.py
> +    user_type = django_filters.CharFilter(method='filter_user_type')
Use MultipleInputFilter instead.

https://github.com/kitab-bazar/server/blob/cc9bc6bd7af57aae21de79fdd8063c883d1a9522/apps/book/filters.py#L18

2022-02-22 10:22 UTC, thenav56 commented on apps/user/filters.py
> +        return queryset.filter(user_type=value)
Not required after using MultipleInputFilter

2022-02-22 10:22 UTC, thenav56 commented on apps/user/filters.py
> +            Q(last_name__icontains=value) |
Let's use this (full_name__icontains) instead of first_name and last_name

2022-02-22 10:22 UTC, thenav56 commented on apps/user/filters.py
>          return queryset.filter(full_name__icontains=value)
Let's remove this now.

2022-02-22 10:22 UTC, thenav56 commented on apps/user/filters.py
>      full_name = django_filters.CharFilter(method='filter_full_name')
Let's remove this now.

2022-02-22 10:22 UTC, thenav56 commented on apps/user/mutations.py
> +    pass
let's remove this

2022-02-22 10:22 UTC, thenav56 commented on apps/user/mutations.py
> +class Verify(CreateUpdateGrapheneMutation):
class VerifyUser

2022-02-22 10:22 UTC, thenav56 commented on apps/user/serializers.py
> +        return attrs
This is not required now.

2022-02-23 15:02 UTC, thenav56 approved these changes

2022-02-23 15:09 UTC, merged